#!/usr/bin/env python3
"""Generate wall diagnostics, resample saved fields, and export run data (stdlib)."""
import argparse
import csv
import json
import math
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
LEVELS = ("coarse", "medium", "fine")


def metadata():
    params = json.loads((ROOT / "case_design/case_params.json").read_text())
    stations = {}
    for step, diameter, bulk in (("expansion", params["d1"], params["U1"]),
                                 ("contraction", params["d2"], params["U2"])):
        for offset in (4, 3, 2):
            stations[f"{step}_{offset}D"] = {
                "step": step, "upstream_diameters": offset,
                "x": params["x_exp" if step == "expansion" else "x_con"] - offset * diameter,
                "diameter": diameter, "bulk_velocity": bulk,
                "wall_radius": diameter / 2 * math.cos(math.radians(params["half_angle_deg"])),
            }
    return {"nu": params["nu"], "stations": stations}


def dictionary(meta, *, standalone=False):
    sets = []
    for name, station in meta["stations"].items():
        radius, x = station["wall_radius"], station["x"]
        # Log-spaced wall distance resolves the inner-scaled plot. These are
        # interpolated samples, not extra mesh cells or evidence of mesh resolution.
        points = []
        for i in range(240):
            distance = radius * 10 ** (-5 + 5 * i / 239)
            r = max(radius - distance, radius * 1e-6)
            points.append(f"({x:.12g} {r:.12g} 0)")
        sets.append(f"{name} {{ type cloud; axis y; points ( {' '.join(points)} ); }}")
    # Normal runs already register these fields through yPlusWall/wallShear.
    # The separate -postProcess dictionary needs its own producers.
    producers = '''upstreamYPlus
{ type yPlus; libs ("libfieldFunctionObjects.so"); writeControl onEnd; }
upstreamShear
{ type wallShearStress; libs ("libfieldFunctionObjects.so"); patches (upperWall);
  writeControl onEnd; }
''' if standalone else '// Reuses fields from the preceding yPlusWall and wallShear function objects.\n'
    return '// Generated by postprocess/sample_wall_profiles.py\n' + producers + '''upstreamWallSurface
{ type surfaces; libs ("libsampling.so"); writeControl onEnd;
  surfaceFormat raw; fields (wallShearStress yPlus); interpolate false;
  surfaces ( wall { type patch; patches (upperWall); } ); }
upstreamProfiles
{ type sets; libs ("libsampling.so"); writeControl onEnd;
  interpolationScheme cellPointFace; setFormat csv; fields (U k epsilon nut);
  sets (\n''' + "\n".join(sets) + '\n); }\n'


def generate():
    params = json.loads((ROOT / "case_design/case_params.json").read_text())
    # Shared by final pressure sampling and the pressure-history line.
    (ROOT / "base_case/system/axis_sampling").write_text(
        '// Generated from case_design/case_params.json; full pipe length.\n'
        'sets ( line { type uniform; axis x;\n'
        '    start (0 0.0002 0);\n'
        f'    end ({params["Ltot"]:.12g} 0.0002 0);\n'
        '    nPoints 1200;\n} );\n'
    )
    target = ROOT / "base_case/system/upstream_diagnostics"
    target.write_text(dictionary(metadata()))
    return target


def latest(directory):
    times = []
    for path in directory.iterdir():
        try:
            if path.is_dir():
                times.append((float(path.name), path))
        except ValueError:
            pass
    if not times:
        raise ValueError(f"No sampled time directories in {directory}")
    return max(times)[1]


def raw(path, count):
    rows = []
    for line in path.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        values = [float(v) for v in line.replace("(", " ").replace(")", " ").split()]
        if len(values) != count or not all(map(math.isfinite, values)):
            raise ValueError(f"Invalid surface row in {path}: {line}")
        rows.append(values)
    if not rows:
        raise ValueError(f"No surface values in {path}")
    return rows


def export(level, data_dir):
    run = ROOT / f"run_{level}"
    source = latest(run / "postProcessing/upstreamProfiles")
    wall_source = latest(run / "postProcessing/upstreamWallSurface")
    if source.name != wall_source.name or source.name != latest(run).name:
        raise ValueError(f"{level}: profiles, wall data and latest solution must have the same time")
    meta = metadata()
    meta["solution_time"] = source.name
    meta["source_case"] = str(run)
    profiles = []
    for station, info in meta["stations"].items():
        paths = list(source.glob(f"{station}_*.csv"))
        if len(paths) != 1:
            raise ValueError(f"Expected one profile for {station} in {source}")
        with paths[0].open() as stream:
            for row in csv.DictReader(stream):
                values = [float(row[key]) for key in ("y", "U_0", "U_1", "U_2", "k", "epsilon", "nut")]
                if not all(map(math.isfinite, values)):
                    raise ValueError(f"Non-finite profile in {paths[0]}")
                profiles.append([station, info["x"], *values])
    shear = raw(wall_source / "wallShearStress_wall.raw", 6)
    yplus = {tuple(row[:3]): row[3] for row in raw(wall_source / "yPlus_wall.raw", 4)}
    walls = [row + [yplus[tuple(row[:3])]] for row in shear]
    data_dir.mkdir(parents=True, exist_ok=True)
    for suffix, header, rows in (
        ("velocity_profiles", ["station", "x", "r", "Ux", "Ur", "Uz", "k", "epsilon", "nut"], profiles),
        ("wall_diagnostics", ["x", "r", "z", "tau_x_over_rho", "tau_r_over_rho", "tau_z_over_rho", "wall_yplus"], walls),
    ):
        output = data_dir / f"{level}_{suffix}.csv"
        with output.open("w", newline="") as stream:
            writer = csv.writer(stream)
            writer.writerow(header)
            writer.writerows(rows)
        print(f"Saved {output} ({len(rows)} samples, time {source.name})")
    (data_dir / f"{level}_wall_metadata.json").write_text(json.dumps(meta, indent=2) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("levels", nargs="*", choices=LEVELS)
    parser.add_argument("--generate", action="store_true", help="Generate base-case axis and wall sampling includes")
    parser.add_argument("--resample", action="store_true", help="Use simpleFoam -postProcess at the latest saved time")
    parser.add_argument("--data-dir", type=Path, default=ROOT / "postprocess/data")
    args = parser.parse_args()
    try:
        if args.generate:
            print(f"Generated {generate()}")
            print(f"Generated {ROOT / 'base_case/system/axis_sampling'}")
            return
        for level in args.levels or LEVELS:
            if args.resample:
                run = ROOT / f"run_{level}"
                config = run / "system/upstreamDiagnosticsDict"
                config.write_text('FoamFile { version 2.0; format ascii; class dictionary; '
                                  'object upstreamDiagnosticsDict; }\nfunctions {\n' + dictionary(metadata(), standalone=True) + '}\n')
                log = run / "log.upstreamDiagnostics"
                with log.open("w") as stream:
                    subprocess.run(["simpleFoam", "-case", str(run), "-postProcess",
                                    "-latestTime", "-dict", str(config)], stdout=stream,
                                   stderr=subprocess.STDOUT, check=True)
            export(level, args.data_dir)
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f"Wall sampling failed: {exc}. See run_<level>/log.upstreamDiagnostics.\n")


if __name__ == "__main__":
    main()
